/// Flutter icons PersonVideo
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PersonVideo
///      fonts:
///       - asset: fonts/PersonVideo.ttf
///
///
///
import 'package:flutter/widgets.dart';

class PersonVideo {
  PersonVideo._();

  static const _kFontFam = 'PersonVideo';
  static const String _kFontPkg = null;

  static const IconData person_video3 =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
